use_frameworks!

target 'PYMethodParser_Example' do
  pod 'PYMethodParser', :path => '../'

  target 'PYMethodParser_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
